InventorySystem/Controllers/SalesController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using InventorySystem.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using Microsoft.AspNetCore.Authorization;

namespace InventorySystem.Controllers
{
    [Authorize]
    public class SalesController : Controller
    {
        private readonly AppdbContext _context;
        public SalesController(AppdbContext context)
        {
            _context = context;
        }
        //Get:Sales/Index
        public IActionResult Index() => View();

        public JsonResult GetAll()
        {
            var sales = _context.Sales.Select(s => new
            {
                Id = s.Id,
                ProductName = s.ProductName,
                Quantity = s.Quantity,
                SalePrice = s.SalePrice,
                SalesDate = s.SalesDate,
                TotalAmount = s.TotalAmount,
                ProductType = s.ProductType,

            }).ToList();

            return Json(sales);
        }

        [HttpGet]
        public IActionResult GetForm(int? id)
        {
            var sales = _context.Sales.Find(id);
            if (sales != null)
            {
                var custId = _context.Billings.Where(b => b.BillId == sales.BillNo).First().CustomerId;
                var customer = _context.Customers.Where(c => c.Id == custId).First().Name;
                sales.Billing.Customer.Name = customer;
            }


            var category = _context.ProductTypes.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.ProductTypeName }).ToList();
            var productName = _context.Products.Select(a => new SelectListItem { Value = a.ProductName, Text = a.ProductName }).ToList();
            ViewBag.Category = category;
            ViewBag.ProductName = productName;
            return PartialView("_form", sales);
        }

        [HttpGet]
        public JsonResult Delete(int id)
        {
            var sales = _context.Sales.Find(id);
            _context.Remove(sales);
            _context.SaveChanges();
            return Json(sales);

        }

        public int SaveCustomer(Sales sales)
        {

            Customer customer = new Customer();
            customer.Name = sales.Billing.Customer.Name;
            customer.PhoneNo = sales.Billing.Customer.PhoneNo;
            customer.Date = sales.SalesDate;
            _context.Add(customer);
            _context.SaveChanges();
            return customer.Id;
        }

        public int SaveBill(Sales sales, int custId)
        {
            Billing billing = new Billing();
            billing.CustomerId = custId;
            billing.BillDate = sales.SalesDate;
            billing.Customer = null;
            _context.Add(billing);
            _context.SaveChanges();
            return billing.BillId;
        }

        [HttpPost]
        public JsonResult SaveForm(Sales sales, int rows)
        {
            if (ModelState.IsValid)
            {
                sales.Profit = (sales.SalePrice - sales.PurchasePrice) * sales.Quantity;
                if (sales.Id == 0)
                {
                    //save and get the billNo and customer first 
                    int billNo = 0;
                    int custId = 0;
                    if (rows == 0)
                    {
                        custId = SaveCustomer(sales);
                        billNo = SaveBill(sales, custId);
                    }
                    else
                        billNo = _context.Billings.OrderByDescending(b => b.BillId).FirstOrDefault().BillId;

                    sales.BillNo = billNo;
                    sales.Billing = null;
                    _context.Add(sales);
                }
                else
                    _context.Update(sales);
                _context.SaveChanges();
            }
            return Json(sales);
        }

        public JsonResult GetProduct(string term)
        {
            return Json(_context.Products.Where(x => x.ProductName.Contains(term)).
                Select(x => new
                {
                    Product = x.ProductName,
                    PurchasePrice = x.PurchasePrice,
                    SalePrice = x.SalePrice,
                    category = x.Category,
                    Quantity = 1
                }).ToList());
        }

    }
}

InventorySystem/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventorySystem.Models;
using InventorySystem.Models.ViewModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace InventorySystem.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly AppdbContext _context;
        private readonly SignInManager<User> _signInManager;

        public UserController(AppdbContext context, SignInManager<User> signInManager)
        {
            _context = context;
            _signInManager = signInManager;
        }


        [HttpGet]
        public IActionResult Index(string msg)
        {
            ViewData["LoginMsg"] = msg;
            return View();
        }

       public IActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                _context.Users.Add(user);
                 _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public IActionResult Logout()
        {
            _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        
    }
}

InventorySystem/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventorySystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.2.1/chart.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Add Product</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Sales</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductType" asp-action="Index">Type</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item nav-item-right ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Create Account</a>
                        </li>

                        <li class="nav-item nav-item-right ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesReport" asp-action="Index">SalesReport</a>
                        </li>

                    </ul>

                    



</div>
       </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - InventorySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   
</body>
</html>